var util = require('../util/util.js'),
	cachePrevUrl = util.cachePrevUrl;

/* Get About Page*/
module.exports.about = function (req, res) {
  cachePrevUrl(req);
  res.render('generic-text', { 
  	user: req.session.account?req.session.account.user:null,
  	title: 'About ReviewU',
  	content: 'ReviewU was created to help people find the best places near their current location. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis facilisis purus, in sollicitudin orci condimentum at. Sed tincidunt urna eu varius accumsan. Suspendisse convallis lobortis consectetur. Ut pellentesque ut nulla nec pretium. Vestibulum semper, elit ac fermentum elementum, tellus erat rhoncus purus, et fringilla ipsum tortor non lacus. Praesent eget quam ut justo cursus ultricies. In ut volutpat nisl. Donec feugiat cursus rhoncus. Suspendisse mollis, nunc in efficitur maximus, massa massa blandit quam, sed pulvinar magna ipsum ac ipsum. Pellentesque venenatis consectetur tortor ac ullamcorper. Sed pulvinar tincidunt leo, sed semper turpis faucibus non. Donec auctor magna suscipit turpis facilisis mollis. Maecenas nisl orci, efficitur sed erat vel, vulputate vulputate turpis. Sed dictum quam at dolor blandit interdum et mollis est. Donec ornare dapibus erat a volutpat. Nullam aliquet congue metus, eu convallis magna. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sagittis facilisis purus, in sollicitudin orci condimentum at. Sed tincidunt urna eu varius accumsan. Suspendisse convallis lobortis consectetur. Ut pellentesque ut nulla nec pretium. Vestibulum semper, elit ac fermentum elementum, tellus erat rhoncus purus, et fringilla ipsum tortor non lacus. Praesent eget quam ut justo cursus ultricies. In ut volutpat nisl. Donec feugiat cursus rhoncus. Suspendisse mollis, nunc in efficitur maximus, massa massa blandit quam, sed pulvinar magna ipsum ac ipsum. Pellentesque venenatis consectetur tortor ac ullamcorper. Sed pulvinar tincidunt leo, sed semper turpis faucibus non. Donec auctor magna suscipit turpis facilisis mollis. Maecenas nisl orci, efficitur sed erat vel, vulputate vulputate turpis. Sed dictum quam at dolor blandit interdum et mollis est. Donec ornare dapibus erat a volutpat. Nullam aliquet congue metus, eu convallis magna.'
  });
};